/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthIdRouteImport } from './routes/auth.$id'
import { Route as DeckDeckIdIndexRouteImport } from './routes/deck.$deckId.index'
import { Route as DeckDeckIdReviewRouteImport } from './routes/deck.$deckId.review'
import { Route as DeckDeckIdCardNewRouteImport } from './routes/deck.$deckId.card.new'
import { Route as ApiAuthCallbackGoogleRouteImport } from './routes/api.auth.callback.google'
import { Route as DeckDeckIdCardCardIdIndexRouteImport } from './routes/deck.$deckId.card.$cardId.index'
import { Route as DeckDeckIdCardCardIdEditRouteImport } from './routes/deck.$deckId.card.$cardId.edit'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIdRoute = AuthIdRouteImport.update({
  id: '/auth/$id',
  path: '/auth/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DeckDeckIdIndexRoute = DeckDeckIdIndexRouteImport.update({
  id: '/deck/$deckId/',
  path: '/deck/$deckId/',
  getParentRoute: () => rootRouteImport,
} as any)
const DeckDeckIdReviewRoute = DeckDeckIdReviewRouteImport.update({
  id: '/deck/$deckId/review',
  path: '/deck/$deckId/review',
  getParentRoute: () => rootRouteImport,
} as any)
const DeckDeckIdCardNewRoute = DeckDeckIdCardNewRouteImport.update({
  id: '/deck/$deckId/card/new',
  path: '/deck/$deckId/card/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthCallbackGoogleRoute = ApiAuthCallbackGoogleRouteImport.update({
  id: '/api/auth/callback/google',
  path: '/api/auth/callback/google',
  getParentRoute: () => rootRouteImport,
} as any)
const DeckDeckIdCardCardIdIndexRoute =
  DeckDeckIdCardCardIdIndexRouteImport.update({
    id: '/deck/$deckId/card/$cardId/',
    path: '/deck/$deckId/card/$cardId/',
    getParentRoute: () => rootRouteImport,
  } as any)
const DeckDeckIdCardCardIdEditRoute =
  DeckDeckIdCardCardIdEditRouteImport.update({
    id: '/deck/$deckId/card/$cardId/edit',
    path: '/deck/$deckId/card/$cardId/edit',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/auth/$id': typeof AuthIdRoute
  '/deck/$deckId/review': typeof DeckDeckIdReviewRoute
  '/deck/$deckId': typeof DeckDeckIdIndexRoute
  '/api/auth/callback/google': typeof ApiAuthCallbackGoogleRoute
  '/deck/$deckId/card/new': typeof DeckDeckIdCardNewRoute
  '/deck/$deckId/card/$cardId/edit': typeof DeckDeckIdCardCardIdEditRoute
  '/deck/$deckId/card/$cardId': typeof DeckDeckIdCardCardIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/auth/$id': typeof AuthIdRoute
  '/deck/$deckId/review': typeof DeckDeckIdReviewRoute
  '/deck/$deckId': typeof DeckDeckIdIndexRoute
  '/api/auth/callback/google': typeof ApiAuthCallbackGoogleRoute
  '/deck/$deckId/card/new': typeof DeckDeckIdCardNewRoute
  '/deck/$deckId/card/$cardId/edit': typeof DeckDeckIdCardCardIdEditRoute
  '/deck/$deckId/card/$cardId': typeof DeckDeckIdCardCardIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/auth/$id': typeof AuthIdRoute
  '/deck/$deckId/review': typeof DeckDeckIdReviewRoute
  '/deck/$deckId/': typeof DeckDeckIdIndexRoute
  '/api/auth/callback/google': typeof ApiAuthCallbackGoogleRoute
  '/deck/$deckId/card/new': typeof DeckDeckIdCardNewRoute
  '/deck/$deckId/card/$cardId/edit': typeof DeckDeckIdCardCardIdEditRoute
  '/deck/$deckId/card/$cardId/': typeof DeckDeckIdCardCardIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/auth/$id'
    | '/deck/$deckId/review'
    | '/deck/$deckId'
    | '/api/auth/callback/google'
    | '/deck/$deckId/card/new'
    | '/deck/$deckId/card/$cardId/edit'
    | '/deck/$deckId/card/$cardId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/settings'
    | '/auth/$id'
    | '/deck/$deckId/review'
    | '/deck/$deckId'
    | '/api/auth/callback/google'
    | '/deck/$deckId/card/new'
    | '/deck/$deckId/card/$cardId/edit'
    | '/deck/$deckId/card/$cardId'
  id:
    | '__root__'
    | '/'
    | '/settings'
    | '/auth/$id'
    | '/deck/$deckId/review'
    | '/deck/$deckId/'
    | '/api/auth/callback/google'
    | '/deck/$deckId/card/new'
    | '/deck/$deckId/card/$cardId/edit'
    | '/deck/$deckId/card/$cardId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SettingsRoute: typeof SettingsRoute
  AuthIdRoute: typeof AuthIdRoute
  DeckDeckIdReviewRoute: typeof DeckDeckIdReviewRoute
  DeckDeckIdIndexRoute: typeof DeckDeckIdIndexRoute
  ApiAuthCallbackGoogleRoute: typeof ApiAuthCallbackGoogleRoute
  DeckDeckIdCardNewRoute: typeof DeckDeckIdCardNewRoute
  DeckDeckIdCardCardIdEditRoute: typeof DeckDeckIdCardCardIdEditRoute
  DeckDeckIdCardCardIdIndexRoute: typeof DeckDeckIdCardCardIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/$id': {
      id: '/auth/$id'
      path: '/auth/$id'
      fullPath: '/auth/$id'
      preLoaderRoute: typeof AuthIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deck/$deckId/': {
      id: '/deck/$deckId/'
      path: '/deck/$deckId'
      fullPath: '/deck/$deckId'
      preLoaderRoute: typeof DeckDeckIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deck/$deckId/review': {
      id: '/deck/$deckId/review'
      path: '/deck/$deckId/review'
      fullPath: '/deck/$deckId/review'
      preLoaderRoute: typeof DeckDeckIdReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deck/$deckId/card/new': {
      id: '/deck/$deckId/card/new'
      path: '/deck/$deckId/card/new'
      fullPath: '/deck/$deckId/card/new'
      preLoaderRoute: typeof DeckDeckIdCardNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/callback/google': {
      id: '/api/auth/callback/google'
      path: '/api/auth/callback/google'
      fullPath: '/api/auth/callback/google'
      preLoaderRoute: typeof ApiAuthCallbackGoogleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deck/$deckId/card/$cardId/': {
      id: '/deck/$deckId/card/$cardId/'
      path: '/deck/$deckId/card/$cardId'
      fullPath: '/deck/$deckId/card/$cardId'
      preLoaderRoute: typeof DeckDeckIdCardCardIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deck/$deckId/card/$cardId/edit': {
      id: '/deck/$deckId/card/$cardId/edit'
      path: '/deck/$deckId/card/$cardId/edit'
      fullPath: '/deck/$deckId/card/$cardId/edit'
      preLoaderRoute: typeof DeckDeckIdCardCardIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SettingsRoute: SettingsRoute,
  AuthIdRoute: AuthIdRoute,
  DeckDeckIdReviewRoute: DeckDeckIdReviewRoute,
  DeckDeckIdIndexRoute: DeckDeckIdIndexRoute,
  ApiAuthCallbackGoogleRoute: ApiAuthCallbackGoogleRoute,
  DeckDeckIdCardNewRoute: DeckDeckIdCardNewRoute,
  DeckDeckIdCardCardIdEditRoute: DeckDeckIdCardCardIdEditRoute,
  DeckDeckIdCardCardIdIndexRoute: DeckDeckIdCardCardIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
